Rosa Maria Sierra Peña // Lab 2

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import preprocessing

Exercise 1. Buying computer

In [2]:
#Step1: Data Entry
age = ['<=30', '<=30', '31…40', '>40', '>40', '>40', '31…40', '<=30', '<=30', '>40', '<=30', '31…40', '31…40', '>40']
income = ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium']
student = ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no']
credit_rating = ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent']
buys_computer = ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']

In [8]:
#Step2: Encode the variables
le = preprocessing.LabelEncoder()
Age_encoded=le.fit_transform(age)
Income_encoded=le.fit_transform(income)
Student_encoded=le.fit_transform(student)
Credit_encoded=le.fit_transform(credit_rating)
label= le.fit_transform(buys_computer)
print(Age_encoded)
print(Income_encoded)
print(Student_encoded)
print(Credit_encoded)
print(label)

[1 1 0 2 2 2 0 1 1 2 1 0 0 2]
[0 0 0 2 1 1 1 2 1 2 2 2 0 2]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]
[1 0 1 1 1 0 0 1 1 1 0 0 1 0]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


Label Codes Meaning:
Age: 0) 31..40 / 1) <=30 / 2) >40
Income: 0)high / 1)low / 2) medium
Student: 0)no / 1)yes
Credit: 0)excellent / 1)fair
Label: 0)no / 1)yes

In [9]:
#Step2: Create an array of the features (x)
features = []

for i in range(len(Age_encoded)):
  features.append([Age_encoded[i],
                   Income_encoded[i],
                   Student_encoded[i],
                   Credit_encoded[i]
                    ])
print(features)

[[1, 0, 0, 1], [1, 0, 0, 0], [0, 0, 0, 1], [2, 2, 0, 1], [2, 1, 1, 1], [2, 1, 1, 0], [0, 1, 1, 0], [1, 2, 0, 1], [1, 1, 1, 1], [2, 2, 1, 1], [1, 2, 1, 0], [0, 2, 0, 0], [0, 0, 1, 1], [2, 2, 0, 0]]


In [10]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,label)

GaussianNB()

In [12]:
#Predict some inputs
predicted= model.predict([[1,0,0,1]])  #<=30,high,no,fair
predicted2= model.predict_proba([[1,0,0,1]]) 
print("Predicted Value:", predicted)
print("The probability of 0(No) are:", predicted2[0][0])
print("The probability of 1(Yes) are:", predicted2[0][1])

Predicted Value: [0]
The probability of 0(No) are: 0.6508949818483578
The probability of 1(Si) are: 0.3491050181516421


For the Point1) who is eligible to buy a computer (buying_computer) (for example, if someone is 25 years old and their income is high, whether he can buy a computer)

We need to train the model only on the features age and income:

In [13]:
features = []

for i in range(len(Age_encoded)):
  features.append([Age_encoded[i],
                   Income_encoded[i]
                    ])
print(features)

[[1, 0], [1, 0], [0, 0], [2, 2], [2, 1], [2, 1], [0, 1], [1, 2], [1, 1], [2, 2], [1, 2], [0, 2], [0, 0], [2, 2]]


In [14]:
model.fit(features,label)

GaussianNB()

In [20]:
predicted= model.predict([[1,0]]) # 1:<=30, 0:High
predicted2= model.predict_proba([[1,1]]) 
print("Predicted Value:", predicted)
print("The probability of 0(No) are:", predicted2[0][0])
print("The probability of 1(Yes) are:", predicted2[0][1])

Predicted Value: [0]
The probability of 0(No) are: 0.3958478887225518
The probability of 1(Si) are: 0.6041521112774483


Exercise 2. Play

In [1]:
#Step 1: Data entry
Outlook = ['sunny','sunny','overcast','rain','rain','rain','overcast','sunny','sunny','rain','sunny','overcast','overcast','rain']
temperature = ['hot','hot','hot','mild','cold','cold','cold','mild','cold','mild','mild','mild','hot','mild']
humidity = ['high','high','high','high','normal','normal','normal','high','normal','normal','normal','high','normal','high']
windy = ['false','true','false','false','false','true','true','false','false','false','true','true','false','true']
play = ['n','n','p','p','p','n','p','n','p','p','p','p','p','n']

In [4]:
#Step2: Data Encode
le = preprocessing.LabelEncoder()
Outlook_encoded=le.fit_transform(Outlook)
Temperature_encoded=le.fit_transform(temperature)
Humidity_encoded=le.fit_transform(humidity)
Windy_encoded=le.fit_transform(windy)
label= le.fit_transform(play)
print(Outlook_encoded)
print(Temperature_encoded)
print(Humidity_encoded)
print(Windy_encoded)
print(label)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]
[0 1 0 0 0 1 1 0 0 0 1 1 0 1]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


Outlook: 0) Overcast 1)Rain 2)Sunny
Temp: 0) Cold 1)Hot 2)Mild
Humidity: 0)High 1)Normal
Windy: 0)False 1)True
Play: 0)N 1)P

In [5]:
#Step3: Features
features = []
for i in range(len(Outlook_encoded)):
  features.append([Outlook_encoded[i],
                   Temperature_encoded[i],
                   Humidity_encoded[i],
                   Windy_encoded[i]
                    ])
print(features)

[[2, 1, 0, 0], [2, 1, 0, 1], [0, 1, 0, 0], [1, 2, 0, 0], [1, 0, 1, 0], [1, 0, 1, 1], [0, 0, 1, 1], [2, 2, 0, 0], [2, 0, 1, 0], [1, 2, 1, 0], [2, 2, 1, 1], [0, 2, 0, 1], [0, 1, 1, 0], [1, 2, 0, 1]]


In [6]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,label)

GaussianNB()

In [7]:
predicted= model.predict([[2,1,0,0]]) # 2:Sunnt, 1:Hot,0:High,0:False
predicted2= model.predict_proba([[2,1,0,0]]) 
print("Predicted Value:", predicted)
print("The probability of 0(No) are:", predicted2[0][0])
print("The probability of 1(Yes) are:", predicted2[0][1])

Predicted Value: [0]
The probability of 0(No) are: 0.8006878062741724
The probability of 1(Si) are: 0.19931219372582767


For the point 2)whether to go to play or not in a different situation? (for example, will you go to play if the outlook is overcast and the humidity is high).

We need to train the model for the features: outlook and humidy

In [8]:
features = []
for i in range(len(Outlook_encoded)):
  features.append([Outlook_encoded[i],
                   Humidity_encoded[i]
                    ])
print(features)

[[2, 0], [2, 0], [0, 0], [1, 0], [1, 1], [1, 1], [0, 1], [2, 0], [2, 1], [1, 1], [2, 1], [0, 0], [0, 1], [1, 0]]


In [9]:
model.fit(features,label)

GaussianNB()

In [11]:
predicted= model.predict([[0,0]]) # 0:Overcast, 0:High
predicted2= model.predict_proba([[0,0]]) 
print("Predicted Value:", predicted)
print("The probability of 0(No) are:", predicted2[0][0])
print("The probability of 1(Yes) are:", predicted2[0][1])

Predicted Value: [1]
The probability of 0(No) are: 0.019464189016725426
The probability of 1(Si) are: 0.9805358109832744
